import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ML Nagpur",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          {/* <Navbar /> */}
          {children}
        </header>
      </body>
    </html>
  );
}
